from teststudent4 import *
s=Student("suzzuki")
p=Professor("yamada")
s2=Student("tarou")
s.set_grade(1)
p.set_room(80)
s2.set_grade(3)
l=Lab()
l.add_member(s)
l.add_member(p)
l.add_member(s2)
l.print_member()
l.mem_sort()
l.print_member()
